Feat/navigation
CSIS-iLab/nuclearnetwork_wp pull request #112
Opened 2021-08-31 20:13 UTC by urchykli

2021-09-07 14:40 UTC, jnschrag requested changes
Really, really nice work here, Lindsay! I'm super proud of what you accomplished with this. This was not an easy feat but it looks great. :)

2021-09-07 14:40 UTC, jnschrag commented on wp-content/themes/csisnuclearnetwork/inc/site-nav-walker.php
> +          $item_output .= '<button>' . $attributes;
I would recommend removing the `$attributes` from the instances where you're using `<button>`. If you look at what the attributes are (defined on lines 86-89), they're pretty link specific, so we can remove them from here.

2021-09-07 14:40 UTC, jnschrag commented on wp-content/themes/csisnuclearnetwork/inc/site-nav-walker.php
> +            <div class='col-xs-12 col-md sub-menu-children' aria-expanded='false'>\n";
Whenever you see classes like `col-xs-12` or `col-md`, you can remove those. The ASP site uses a Bootstrap derivative stylesheet based on flexbox that has a 12 column layout and that's what those classes are from. NN doesn't use that, so go ahead and remove it.

2021-09-07 14:40 UTC, jnschrag commented on wp-content/themes/csisnuclearnetwork/assets/_scss/layout/_header.scss
>    &__menu {
I would maybe recommend moving the navigation styles into their own file and keeping the `_header.scss` file more layout + logo stuff, but up to you.

Don't forget to add a cursor to the buttons/links in the menu - the browser won't add that automatically to buttons, so you'll need to do it.

2021-09-08 19:42 UTC, urchykli commented
This PR handles the navigation menu. It does not handle the rest of the site header including the scroll functionality and the search bar.

The submenus are designed to appear and disappear on click or focus rather than hover.

2021-09-08 20:16 UTC, jnschrag requested changes
This is looking really good, Lindsay. A couple of tweaks and I think this is golden. Some of these could definitely be nice to haves too. :)

- [x] The spacing between "All Analysis" and "All Series" is off. This is the CSS Grid trying to align the items. If you change the "Popular Topics" so it spans 3 rows instead of 2, it'll fix itself.
- [ ] The dropdown is missing a carrot/triangle at the top on larger screens
- [ ] Check the hover color of the post title of the featured post
- [ ] I'm also not seeing a change in the hover state on the links in the drop down menus
- [ ] On mobile we're missing an overlay over the content when the menu is open. A common request is to "freeze" the body so the user can't scroll on anything but the menu when the menu is open. I like the [body-scroll-lock](https://github.com/willmcpo/body-scroll-lock) library for that. You would add the `disableBodyScroll` to the same event listeners that open & close the menu.

2021-09-13 22:38 UTC, merged