Feat/post content style
CSIS-iLab/nuclearnetwork_wp pull request #85
Opened 2021-07-26 13:52 UTC by KaiElwood

Added all required post styles. #62

2021-07-27 16:15 UTC, urchykli requested changes
Nice job on this, Kai!  Just a few comments and questions including the ones inline.  Thanks!

- On line 53, let's remove `ul`, since the correct color is added on line 69.
- If you aren't using the commented out code, please delete it.

2021-07-27 16:15 UTC, urchykli commented on wp-content/themes/csisnuclearnetwork/assets/_scss/pages/single.scss
> +      // @include font-size(18px);
Let's remove this unused code.

2021-07-27 16:15 UTC, urchykli commented on wp-content/themes/csisnuclearnetwork/assets/_scss/pages/single.scss
>        font-weight: 400;
We can remove this.

2021-07-27 16:15 UTC, urchykli commented on wp-content/themes/csisnuclearnetwork/assets/_scss/pages/single.scss
> +    // }
Did Christina say we aren't using the icon for external links?

2021-07-30 20:03 UTC, urchykli requested changes
Nice work, Kai!  We still need to remove the `ul` from line 53 and make the small inline changes, but then we're ready to merge.

2021-07-30 20:03 UTC, urchykli commented on wp-content/themes/csisnuclearnetwork/assets/_scss/pages/single.scss
> +      &:hover::after {
We need a focus state as well.

2021-08-03 17:21 UTC, KaiElwood commented on wp-content/themes/csisnuclearnetwork/assets/_scss/pages/single.scss
>        &:visited {
Got it

2021-08-04 13:36 UTC, urchykli approved these changes

2021-08-04 13:36 UTC, merged