Feat/post media
CSIS-iLab/nuclearnetwork_wp pull request #89
Opened 2021-07-29 17:11 UTC by HP4k1h5

Creates scss class and lazyblock code for media components in posts.

2021-07-29 19:03 UTC, urchykli requested changes
Nice first pass on this, Bob!  In addition to the comment below about alignments, I left a few inline comments.

When someone adds a blockquote to a post, they should be choosing between left and right aligned.  Since we can't force them to pick one, the default should be right aligned and if the others are picked it should align accordingly.  Also, when the alignments are added, they are applied at a smaller breakpoint than they should be.  This is because other elements that have these alignements (images, etc.) float at smaller breakpoints.  That being said, you'll need to adjust the `--margin-text-side` and --margin-gutter-side` variables in this file to work with the alignments [here](https://github.com/CSIS-iLab/nuclearnetwork_wp/blob/cd1b283c23447a2f4d2f47de3a3a4dfa2553b6cc/wp-content/themes/csisnuclearnetwork/assets/_scss/blocks/post.scss#L37).

2021-07-29 19:31 UTC, HP4k1h5 commented on wp-content/themes/csisnuclearnetwork/assets/_scss/blocks/post/_blockquote.scss
>        font-style: normal;
author name appears in italics without `font-style: normal`, but i can't see why looking up the inheritance chain.

2021-08-03 17:07 UTC, urchykli commented on wp-content/themes/csisnuclearnetwork/assets/_scss/blocks/post/_blockquote.scss
>        font-style: normal;
Ah good catch! It's the default style for `cite`

2021-08-03 19:07 UTC, urchykli requested changes
We're getting there!

When I said, you'll need to adjust the `--margin-text-side` and `--margin-gutter-side` variables, I meant for the small and medium breakpoints. Since it should be centered on these screen sizes, both of the margin variables should be set to `auto` and the float should be removed.  

Also, the `max-width` doesn't apply until the medium breakpoint.

Example of the margins:
```
@include breakpoint('small') {
      --margin-text-side: auto;
      --margin-gutter-side: auto;
      float: none !important;
      max-width: 100%;
    }

@include breakpoint('medium') {
      --margin-text-side: auto;
      --margin-gutter-side: auto;
      float: none !important;
      max-width: rem(340);
    }
```

2021-08-25 17:59 UTC, urchykli requested changes
This is looking really good, Bob! 

**Note**: I added the correct full and wide width mixins and the background color to make it easier to see what you're doing, so you'll need to do a git pull.  

Other than the few inline comments, I noticed the following things.

- [x] Caption styling for images and videos
- [x] Yellow line above the caption for images.
- [x] The right and left aligned elements should match up with the edge of wide aligned elements, so we'll need to adjust those a little.  
- [ ] Blockquote blocks are adding `<meta charset="utf-8">` to the beginning of the quote on my local and on dev.

Thank you!

2021-09-01 15:04 UTC, merged